//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.15 at 09:50:58 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/demo/")
package org.example.demo;
